schema_version = "1.0.0"

id = "sonic_rivals_importer"
version = "0.1.0"
name = "Sonic Rivals Importer"
tagline = "Import models from Sonic: Rivals"
maintainer = "jmancoder"
type = "add-on"
tags = ["Import-Export", "Mesh"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
